// <auto-generated />
using AHAS.WS.INFRA.DATA.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AHAS.WS.INFRA.DATA.Migrations
{
    [DbContext(typeof(DataBaseSQLContext))]
    [Migration("20190501234702_InicialMigration")]
    partial class InicialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AHAS.WS.LOGIC.DOMAIN.Entities.ContaContabil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Balanco")
                        .IsRequired()
                        .HasColumnName("Balanco")
                        .HasColumnType("VARCHAR(75)")
                        .HasMaxLength(75);

                    b.Property<long>("Conta")
                        .HasColumnName("Conta");

                    b.HasKey("Id");

                    b.HasIndex("Conta")
                        .IsUnique();

                    b.ToTable("TbContaContabil");
                });

            modelBuilder.Entity("AHAS.WS.LOGIC.DOMAIN.Entities.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Denominacao")
                        .IsRequired()
                        .HasColumnName("Denominacao")
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnName("Sigla")
                        .HasColumnType("VARCHAR(2)")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("TbDocumento");
                });

            modelBuilder.Entity("AHAS.WS.LOGIC.DOMAIN.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnName("CNPJ")
                        .HasColumnType("VARCHAR(14)")
                        .HasMaxLength(14);

                    b.Property<string>("Centro")
                        .IsRequired()
                        .HasColumnName("Centro")
                        .HasColumnType("VARCHAR(4)")
                        .HasMaxLength(4);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnName("Codigo")
                        .HasColumnType("VARCHAR(4)")
                        .HasMaxLength(4);

                    b.Property<string>("IE")
                        .IsRequired()
                        .HasColumnName("IE")
                        .HasColumnType("VARCHAR(14)")
                        .HasMaxLength(14);

                    b.Property<string>("LocalNegocio")
                        .IsRequired()
                        .HasColumnName("LocalNegocio")
                        .HasColumnType("VARCHAR(4)")
                        .HasMaxLength(4);

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnName("Sigla")
                        .HasColumnType("VARCHAR(15)")
                        .HasMaxLength(15);

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnName("UF")
                        .HasColumnType("VARCHAR(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnName("Unidade")
                        .HasColumnType("VARCHAR(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.HasIndex("IE")
                        .IsUnique();

                    b.ToTable("TbEmpresa");
                });

            modelBuilder.Entity("AHAS.WS.LOGIC.DOMAIN.Entities.EstadoSAP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CodigoSAP")
                        .HasColumnName("CodigoSAP");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnName("Estado")
                        .HasColumnType("VARCHAR(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnName("Sigla")
                        .HasColumnType("VARCHAR(2)")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("TbEstadoSAP");
                });
#pragma warning restore 612, 618
        }
    }
}
